#################################################
# Site settings
#################################################

title: HTACG
email: balthisar@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This site is the Github home of HTACG, the W3C HTML Tidy Advocacy
  Community Group.
baseurl: ""                 # the subpath of your site, e.g. /blog/
url: "http://www.htacg.org" # the base hostname & protocol for your site


#################################################
# Administrator Information
#################################################

twitter_username: balthisar
github_username:  balthisar


#################################################
# Conversion settings
#################################################

markdown:    kramdown
highlighter: pygments
lsi:         false
excerpt_separator: "\n\n"

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6


#################################################
# File Locations
#################################################

source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
data_source: ./_data
collections: null


#################################################
# Defaults
#################################################

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"


#################################################
# Other Goodies
#################################################
gems:
  - jekyll-sitemap
  - jekyll-mentions
